name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v2
        with:
          xcode-version: '15'  # or specify the version you're using

      - name: Install Dependencies (CocoaPods)
        if: exists('Podfile')
        run: |
          sudo gem install cocoapods
          pod install

      # If you're using Swift Package Manager instead, uncomment:
      # - name: Resolve Swift Packages
      #   run: swift package resolve

      - name: Build
        run: |
          xcodebuild \
            -project appdb.xcodeproj \
            -scheme appdb \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.4' \
            clean build \
            ONLY_ACTIVE_ARCH=YES \
            CODE_SIGNING_ALLOWED=NO

      - name: Run Tests
        if: |
          test -d appdbTests || test -d appdbUITests
        run: |
          xcodebuild \
            -project appdb.xcodeproj \
            -scheme appdb \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.4' \
            test \
            ONLY_ACTIVE_ARCH=YES \
            CODE_SIGNING_ALLOWED=NO
